### ISSUE TITLE
不支持Python3

### ISSUE THREAD

**Issue by seoul2k** [livz/cloacked-pixel#10]
python3 /Users/seoul1k/Downloads/cloacked-pixel-master/lsb.py '/Users/seoul1k/Desktop/截屏2022-05-08 12.26.41.png' index.txt 123
  File "/Users/seoul1k/Downloads/cloacked-pixel-master/lsb.py", line 56
    print "[*] Input image size: %dx%d pixels." % (width, height)
          ^
SyntaxError: invalid syntax
改成python3版本后，又报:
python3 /Users/seoul1k/Downloads/cloacked-pixel-master/lsb.py hide '/Users/seoul1k/Desktop/截屏2022-05-08 12.26.41.png' ./Desktop/index.txt 123
[*] Input image size: 116x48 pixels.
[*] Usable payload size: 2.04 KB.
[+] Payload size: 0.006 KB
Traceback (most recent call last):
  File "/Users/seoul1k/Downloads/cloacked-pixel-master/lsb.py", line 192, in <module>
    embed(sys.argv[2], sys.argv[3], sys.argv[4])
  File "/Users/seoul1k/Downloads/cloacked-pixel-master/lsb.py", line 67, in embed
    data_enc = cipher.encrypt(data)
  File "/Users/seoul1k/Downloads/cloacked-pixel-master/crypt.py", line 16, in encrypt
    raw = self._pad(raw)
  File "/Users/seoul1k/Downloads/cloacked-pixel-master/crypt.py", line 27, in _pad
    return s + (self.bs - len(s) % self.bs) * chr(self.bs - len(s) % self.bs)
TypeError: can't concat str to bytes

**Comment by LanYunDev** [comment]
一样

**Comment by constantinedev** [comment]
自己加返D()係print後面啦

**Comment by kfbfarley** [comment]
there is a commit/pr with the solution [here](https://github.com/livz/cloacked-pixel/pull/4)

**Comment by NatteeSetobol** [comment]
Fixed for Python 3: https://github.com/NatteeSetobol/cloacked-pixel . I tried fix it using chat-gpt but it didn't work as well so I so I learned how it works and now it runs on python3.

**Comment by 2477231995** [comment]
> 已修复 Python 3：https://github.com/NatteeSetobol/cloacked-pixel 。我尝试使用 chat-gpt 修复它，但它的效果不佳，所以我学习了它的工作原理，现在它在 python3 上运行。

Very impressive, thank you, big shot

**Comment by aristorechina** [comment]
I also encountered the same issue, so I recently fixed it. It now perfectly supports Python 3. Meanwhile, I have added a Chinese translation to the README.
我也遇到了这个问题，于是我最近修复了它，使其支持 Python 3。同时我还为 README 添加了中文翻译。

[aristorechina/cloacked-pixel: LSB steganography and detection](https://github.com/aristorechina/cloacked-pixel)
